### Verify
POST http://localhost:6181/customer-insight-platform/email/verify
content-type: application/json
Authorization: fake-token

{
  "email" : "test@test.com"
}

### Verify Passcode
POST http://localhost:6183/customer-insight-platform/email/verify/passcode
content-type: application/json
Authorization: fake-token

{
  "email" : "test1@test.com",
  "passcode":"EFMFGZ"
}


### Notifications
GET http://localhost:6183/customer-insight-platform/email/notifications/ecf20f0a-86af-4ebf-9012-e48bc6a31174
content-type: application/json
Authorization: fake-token

